"""
Pydantic schemas package for request/response validation.
"""

from .user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserLogin,
    UserInDB,
    UserResponse,
    Token,
    TokenPayload,
    UserRoleUpdate,
    UserStatusUpdate,
    UserTeamAssignment,
    UserProfile,
    UserProfileUpdate,
    UserPreferences,
    PasswordChange,
    NotificationPreferences,
)

from .team import (
    TeamBase,
    TeamCreate,
    TeamUpdate,
    TeamResponse,
    TeamDetailResponse,
    TeamMemberResponse,
    TeamMemberAdd,
    TeamMemberRemove,
    TeamMemberUpdate,
    TeamAnalytics,
    TeamComparisonMetrics,
    TeamPerformanceMetrics,
    DashboardMetrics,
    PlatformAnalytics,
    PlatformStatistics,
    TeamListQuery,
    TeamListResponse,
)

from .file_batch import (
    BatchStatusEnum,
    FileStatusEnum,
    BatchFileBase,
    BatchFileCreate,
    BatchFileUpdate,
    BatchFileResponse,
    BatchFileDetailResponse,
    FileBatchBase,
    FileBatchCreate,
    FileBatchUpdate,
    FileBatchResponse,
    FileBatchDetailResponse,
    FileUploadRequest,
    FileUploadResponse,
    BatchStatusResponse,
    FileAnalysisRequest,
    BatchAnalysisRequest,
    FileValidationResult,
    BatchValidationResult,
)

from .audit_log import (
    AuditActionEnum,
    AuditStatusEnum,
    ResourceTypeEnum,
    AuditLogBase,
    AuditLogCreate,
    AuditLogResponse,
    AuditLogDetailResponse,
    AuditLogQuery,
    AuditLogListResponse,
    AuditLogStatistics,
    UserActivitySummary,
    TeamActivitySummary,
    AuditLogExportRequest,
    AuditLogExportResponse,
)

__all__ = [
    # User schemas
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserLogin",
    "UserInDB",
    "UserResponse",
    "Token",
    "TokenPayload",
    "UserRoleUpdate",
    "UserStatusUpdate",
    "UserTeamAssignment",
    "UserProfile",
    "UserProfileUpdate",
    "UserPreferences",
    "PasswordChange",
    "NotificationPreferences",
    
    # Team schemas
    "TeamBase",
    "TeamCreate",
    "TeamUpdate",
    "TeamResponse",
    "TeamDetailResponse",
    "TeamMemberResponse",
    "TeamMemberAdd",
    "TeamMemberRemove",
    "TeamMemberUpdate",
    "TeamAnalytics",
    "TeamComparisonMetrics",
    "TeamPerformanceMetrics",
    "DashboardMetrics",
    "PlatformAnalytics",
    "PlatformStatistics",
    "TeamListQuery",
    "TeamListResponse",
    
    # File batch schemas
    "BatchStatusEnum",
    "FileStatusEnum",
    "BatchFileBase",
    "BatchFileCreate",
    "BatchFileUpdate",
    "BatchFileResponse",
    "BatchFileDetailResponse",
    "FileBatchBase",
    "FileBatchCreate",
    "FileBatchUpdate",
    "FileBatchResponse",
    "FileBatchDetailResponse",
    "FileUploadRequest",
    "FileUploadResponse",
    "BatchStatusResponse",
    "FileAnalysisRequest",
    "BatchAnalysisRequest",
    "FileValidationResult",
    "BatchValidationResult",
    
    # Audit log schemas
    "AuditActionEnum",
    "AuditStatusEnum",
    "ResourceTypeEnum",
    "AuditLogBase",
    "AuditLogCreate",
    "AuditLogResponse",
    "AuditLogDetailResponse",
    "AuditLogQuery",
    "AuditLogListResponse",
    "AuditLogStatistics",
    "UserActivitySummary",
    "TeamActivitySummary",
    "AuditLogExportRequest",
    "AuditLogExportResponse",
]
